version: '3.9'

services:
  app:
    platform: linux/amd64
    env_file:
      - .env
    container_name: lovelystay-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "7575:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "export PGHOST=$DB_HOST PGPORT=$DB_PORT PGDATABASE=$DB_DATABASE PGUSER=$DB_USER PGPASSWORD=$DB_PASSWORD && npm run migrate:up && npm run build && node dist/main.js"
    stdin_open: true
    tty: true

  db:
    platform: linux/amd64
    env_file:
      - .env
    container_name: lovelystay-db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:- default_password}
      POSTGRES_USER: ${DB_USER:- default_user}
      POSTGRES_DB: ${DB_DATABASE:- default_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "9432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lovelystay-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
  node_modules:
